:arrow_up: Update CI workflow to use Ubuntu 24.04 and added documentation checks

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,18 +14,30 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+  build_and_test:
+    runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@v4
       - uses: actions-rust-lang/setup-rust-toolchain@v1
       - uses: extractions/setup-just@v2
+      - uses: harehare/setup-mq@v1
       - name: Install cargo-llvm-cov
         uses: taiki-e/install-action@cargo-llvm-cov
+      - name: Install cargo-readme
+        run: cargo install cargo-readme
       - name: Build
         run: just build
       - name: Run tests
         run: just test
+      - name: Check docs
+        run: just docs
+      - name: Check for diffs in docs
+        run: |
+          if [[ -n $(git status --porcelain docs/) ]]; then
+            echo "Error: Changes detected in docs directory. Please commit these changes."
+            git status --porcelain docs/
+            exit 1
+          fi
       - name: Generate code coverage
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
